### ISSUE TITLE
Build error fmt

### ISSUE THREAD

**Issue by e-sempertegui** [versatran01/llol#6]
Hi,

I'm trying to build the package, however I get the following build error related to `fmt` : 

```../fmt/include/fmt/core.h: In instantiation of ‘constexpr fmt::v8::detail::value<Context> fmt::v8::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; fmt::v8::detail::type <anonymous> = (fmt::v8::detail::type)15; T = const Eigen::Transpose<const Eigen::Matrix<double, 4, 1> >&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’:
../fmt/include/fmt/core.h:1839:77:   required from ‘constexpr fmt::v8::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const double&, const Eigen::Transpose<const Eigen::Matrix<double, 4, 1, 0, 4, 1> >&, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >&, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >&}; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {double, Eigen::Transpose<const Eigen::Matrix<double, 4, 1, 0, 4, 1> >, Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >, Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >}]’
../fmt/include/fmt/core.h:3128:17:   required from ‘std::__cxx11::string fmt::v8::format(fmt::v8::format_string<T ...>, T&& ...) [with T = {const double&, const Eigen::Transpose<const Eigen::Matrix<double, 4, 1, 0, 4, 1> >, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >}; std::__cxx11::string = std::__cxx11::basic_string<char>; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const double&, const Eigen::Transpose<const Eigen::Matrix<double, 4, 1, 0, 4, 1> >, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> >, const Eigen::Transpose<const Eigen::Matrix<double, 3, 1, 0, 3, 1> > >]’
../llol/sv/llol/imu.cpp:75:37:   required from here
../fmt/include/fmt/core.h:3128:44:   in constexpr expansion of ‘fmt::v8::make_format_args<>((* & args#0), (* & args#1), (* & args#2), (* & args#3))’
../fmt/include/fmt/core.h:1711:3: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
```

I'm running Ubuntu 18.04, with the latest master from `fmt` built from source. Note that this error happens at a couple of places in `imu.cpp`, I'm just showing you one for simplicity. 

Any help or suggestion is appreciated!

**Comment by versatran01** [comment]
Just include fmt/ostream.h in those files.

**Comment by e-sempertegui** [comment]
Hey! Thanks for your input.

That header is included already in the source file so I'm not sure what you mean, see https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/imu.cpp#L3

**Comment by versatran01** [comment]
Try including both core.h and ostream.h?

**Comment by iandouglas96** [comment]
I have found it to work well with fmt 8.1.1 (the most recent release) and make sure to compile fmt with `DCMAKE_POSITION_INDEPENDENT_CODE=True`.
